#!/usr/bin/python

#Simple Program to Encode and Decode data 

import re
import sys

alphavalue = {'a':'1','b':'2','c':'3','d':'4','e':'5','f':'6','g':'7','h':'8','i':'9','j':'10','k':'11','l':'12','m':'13','n':'14','o':'15','p':'16','q':'17','r':'18','s':'19','t':'20','u':'21','v':'22','w':'23','x':'24','y':'25','z':'26','?':'27','.':'28',',':'30'}

def encode(raw_data):
	list_data = list(raw_data)
	encoded = []

	for i in list_data:
		for j in alphavalue:
			if i == j:
				encoded.append(alphavalue[j])
				encoded.append('*')
		if i == ' ':
			encoded.append('-*')
	encoded = ''.join(encoded)
	print "Copy, Paste the below encoded data to your friend and tell your friend to copy paste the same as input to the program"
	print encoded
	

def decode(raw_data):
	list_data = re.split('\*',raw_data)
	decoded = []

	for i in list_data:
		for j in alphavalue:
			if i == alphavalue[j]:
				decoded.append(j)
		if i == '*':
			decoded.append("")
		elif i == '-':
			decoded.append(' ')
	decoded = ''.join(decoded)
	print "Here is your Message:"
	print decoded.title()

def main():
	try:
		raw_data = sys.argv[1]
		raw_data = raw_data.lower()
		if re.search('a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z| ',raw_data[0]):
			encode(raw_data)
		else:
			decode(raw_data)
	except IndexError:
		print "\nSorry, No message given! Nothing to do.\n"
		print "Usage: secret 'Your message or secret message'"
		print "Ex1: secret 'Hey dude, how are you?\t (or)" + "\nEx2: secret The_secret_message_within_qoutes_that_you_got_after_running_the_Ex1_example\n"

if __name__ == "__main__":
	main()